### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by m-raafat-abdelkader**

### CODE REVIEW

**Comment by m-raafat-abdelkader** [comment]
I didn't know that it refers to the 'DDL' action. Thanks 😊

**Comment by dpage** [comment]
I still think you should update it - just not the way you originally suggested :-). Either of my suggestions would work, or feel free to propose something else.

**Comment by m-raafat-abdelkader** [comment]
I will do my best 😊

**Comment by m-raafat-abdelkader** [comment]
I've created a new pull request with new suggestions :)
Ref: "Update README.md #8"

**Pull request closed without merging**
